import {StyleSheet} from 'react-native';
import {DRAWER_WIDTH} from '../constants/layout';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  content: {
    padding: 16,
    gap: 12,
    paddingBottom: 24,
  },
  screenGestureLayer: {
    flex: 1,
  },
  totalCard: {
    backgroundColor: '#e0f2fe',
    borderRadius: 14,
    padding: 14,
    gap: 6,
  },
  topMenuContainer: {
    position: 'relative',
    zIndex: 10,
    minHeight: 1,
  },
  edgeMenuActivator: {
    position: 'absolute',
    top: '50%',
    left: 0,
    marginTop: -42,
    width: 30,
    height: 84,
    zIndex: 35,
  },
  edgeMenuTapArea: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    zIndex: 30,
  },
  drawerOverlayTouch: {
    flex: 1,
  },
  sideDrawer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: DRAWER_WIDTH,
    backgroundColor: '#e2e8f0',
    borderRightWidth: 1,
    borderRightColor: '#cbd5e1',
    zIndex: 40,
    paddingTop: 56,
  },
  sideDrawerHeader: {
    paddingHorizontal: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
  },
  sideDrawerTitle: {
    color: '#0f172a',
    textAlign: 'right',
    fontWeight: '700',
    fontSize: 20,
  },
  topMenuItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
  },
  topMenuItemText: {
    color: '#0f172a',
    textAlign: 'right',
    fontWeight: '600',
  },
  topMenuItemLast: {
    borderBottomWidth: 0,
  },
  totalLabel: {
    color: '#0f4c81',
    fontSize: 14,
    textAlign: 'right',
  },
  totalValue: {
    color: '#0c4a6e',
    fontSize: 30,
    fontWeight: '700',
    textAlign: 'right',
  },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'right',
    marginBottom: 8,
  },
  label: {
    color: '#334155',
    textAlign: 'right',
    fontSize: 14,
  },
  input: {
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbeafe',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#0f172a',
    height: 48,
  },
  datePickerBtn: {
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbeafe',
    paddingHorizontal: 12,
    height: 48,
    justifyContent: 'center',
  },
  datePickerBtnText: {
    color: '#0f172a',
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  pickerWrap: {
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbeafe',
    overflow: 'hidden',
    height: 48,
    justifyContent: 'center',
  },
  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  compactFieldsRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 8,
  },
  compactField: {
    flex: 1,
  },
  customSourceCard: {
    backgroundColor: '#e2e8f0',
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  flexInput: {
    flex: 1,
  },
  primaryBtn: {
    marginTop: 6,
    backgroundColor: '#0284c7',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    flex: 1,
  },
  secondaryBtn: {
    marginTop: 6,
    backgroundColor: '#1d4ed8',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  cancelBtn: {
    marginTop: 6,
    backgroundColor: '#64748b',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  btnText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  debtSummaryCard: {
    backgroundColor: '#eef2ff',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  debtCard: {
    backgroundColor: '#fff7ed',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  balanceActionCard: {
    backgroundColor: '#f0f9ff',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  moneySummaryRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingVertical: 8,
  },
  moneySummaryRowLast: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  moneySummaryLabel: {
    color: '#334155',
    fontWeight: '600',
  },
  moneySummaryValue: {
    color: '#0f766e',
    fontWeight: '700',
  },
  negativeValue: {
    color: '#dc2626',
  },
  warningValue: {
    color: '#d97706',
  },
  debtItem: {
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  balanceHistoryItem: {
    backgroundColor: '#e0f2fe',
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  debtItemRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  debtItemLabel: {
    color: '#7c2d12',
    fontWeight: '600',
  },
  debtItemValue: {
    color: '#431407',
    fontWeight: '500',
    maxWidth: '70%',
    textAlign: 'right',
  },
  deleteBtnLarge: {
    marginTop: 6,
    backgroundColor: '#dc2626',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  emptyText: {
    color: '#64748b',
    textAlign: 'center',
  },
});

export default styles;
